In [2]:
import rispy
import pandas as pd
from pathlib import Path
import os
import sys

In [3]:
os.chdir("../")
print(f"Current working directory: {os.getcwd()}")

Current working directory: D:\projects\MateReview

In [11]:
filepath = Path("data/REV1-SCOPUS-1/2026-03-26_Export.ris")
with open(filepath, "r", encoding="utf-8") as f:
    entries = rispy.load(f)

In [12]:
# Turn into dataframe
df = pd.DataFrame(entries)
print(f"Columns: {df.columns}")
df.head()

Columns: Index(['type_of_reference', 'authors', 'title', 'year', 'secondary_title',
       'volume', 'number', 'custom7', 'doi', 'urls', 'author_address',
       'abstract', 'keywords', 'publisher', 'issn', 'custom2', 'language',
       'alternate_title1', 'type_of_work', 'name_of_database', 'notes',
       'secondary_authors', 'start_page', 'end_page', 'short_title'],
      dtype='str')

,type_of_reference,authors,title,year,secondary_title,volume,number,custom7,doi,urls,...,custom2,language,alternate_title1,type_of_work,name_of_database,notes,secondary_authors,start_page,end_page,short_title
0,JOUR,"[Li, Z., Scandolo, S.]",A physics-informed long-range polarizable pote...,2026,Journal of Chemical Physics,164,4,044107,10.1063/5.0292167,[https://www.scopus.com/inward/record.uri?eid=...,...,41574796,English,J Chem Phys,Article,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN
1,JOUR,"[Yan, J., Bai, L., Liu, H., Zhang, Z., Tang, Y...",In-Process Tool Wear Prediction Enabled by Phy...,2026,IEEE Transactions on Industrial Informatics,NaN,NaN,NaN,10.1109/TII.2026.3658032,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,IEEE Trans. Ind. Inf.,Article,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN
2,CONF,"[Lv, M., Gu, M.-Y., Xu, X.]",Research on accurate prediction method of disp...,2026,Proceedings of SPIE - The International Societ...,14069,NaN,140690D,10.1117/12.3106792,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,Proc SPIE Int Soc Opt Eng,Conference paper,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,"[Manoj G., Xu J.]",NaN,NaN,NaN
3,JOUR,"[Lüthje, J.T., Langiu, M., Mitsos, A.]",Working fluid screening for ORC-based Carnot b...,2026,Optimization and Engineering,27,1,NaN,10.1007/s11081-025-10026-9,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,Optim. Eng.,Article,Scopus,[Export Date: 24 March 2026; Cited By: 1; Corr...,NaN,587,616,NaN
4,JOUR,"[Choi, K., Joe, J., Ha, S., Lee, D., Mun, J.]",A non-intrusive experimental study on the ther...,2026,Energy and Buildings,359,NaN,117257,10.1016/j.enbuild.2026.117257,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,Energy Build.,Article,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN

In [14]:
df.columns.sort_values()

Index(['abstract', 'alternate_title1', 'author_address', 'authors', 'custom2',
       'custom7', 'doi', 'end_page', 'issn', 'keywords', 'language',
       'name_of_database', 'notes', 'number', 'publisher', 'secondary_authors',
       'secondary_title', 'short_title', 'start_page', 'title',
       'type_of_reference', 'type_of_work', 'urls', 'volume', 'year'],
      dtype='str')

In [20]:
# Show where custom7 is nan
df.loc[df["custom7"].isna(), "custom2"]

1       NaN
3       NaN
12      NaN
15      NaN
29      NaN
       ...
9695    NaN
9696    NaN
9697    NaN
9698    NaN
9699    NaN
Name: custom2, Length: 5749, dtype: str

In [21]:
# Filter by year > 2021, type is Jurnal and has DOI
filtered_df = df[(df["year"].astype(int) > 2021) & (df["type_of_reference"] == "JOUR") & (df["doi"].notna())]
print(f"Filtered entries: {len(filtered_df)}")
filtered_df.head()

Filtered entries: 3763

,type_of_reference,authors,title,year,secondary_title,volume,number,custom7,doi,urls,...,custom2,language,alternate_title1,type_of_work,name_of_database,notes,secondary_authors,start_page,end_page,short_title
0,JOUR,"[Li, Z., Scandolo, S.]",A physics-informed long-range polarizable pote...,2026,Journal of Chemical Physics,164,4,044107,10.1063/5.0292167,[https://www.scopus.com/inward/record.uri?eid=...,...,41574796,English,J Chem Phys,Article,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN
1,JOUR,"[Yan, J., Bai, L., Liu, H., Zhang, Z., Tang, Y...",In-Process Tool Wear Prediction Enabled by Phy...,2026,IEEE Transactions on Industrial Informatics,NaN,NaN,NaN,10.1109/TII.2026.3658032,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,IEEE Trans. Ind. Inf.,Article,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN
3,JOUR,"[Lüthje, J.T., Langiu, M., Mitsos, A.]",Working fluid screening for ORC-based Carnot b...,2026,Optimization and Engineering,27,1,NaN,10.1007/s11081-025-10026-9,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,Optim. Eng.,Article,Scopus,[Export Date: 24 March 2026; Cited By: 1; Corr...,NaN,587,616,NaN
4,JOUR,"[Choi, K., Joe, J., Ha, S., Lee, D., Mun, J.]",A non-intrusive experimental study on the ther...,2026,Energy and Buildings,359,NaN,117257,10.1016/j.enbuild.2026.117257,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,Energy Build.,Article,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN
5,JOUR,"[Kumar Yadav, A.]",Artificial Intelligence in Accelerating Materi...,2026,ChemistrySelect,11,7,e07191,10.1002/slct.202507191,[https://www.scopus.com/inward/record.uri?eid=...,...,NaN,English,ChemistrySelect,Review,Scopus,[Export Date: 24 March 2026; Cited By: 0; Corr...,NaN,NaN,NaN,NaN

In [9]:
filtered_df = df[(df["year"] > 2021) & (df["type_of_reference"] == "JOUR") & (df["doi"].notna())]

TypeError: '>' not supported between instances of 'str' and 'int'